aws:
    credentials:
        access-key: 'dummy'
        secret-key: 'dummy'

spring:
    flyway:
        enabled: false
    jpa:
        generate-ddl: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
