management:
    endpoints:
        web:
            exposure:
                include: info,health
spring:
    datasource:
        username: bart
        password: helloworld2
        jdbc-url: jdbc:mysql://kubernetes.docker.internal:3306/blackarrowlocal?useLegacyDatetimeCode=false
        url: ${spring.datasource.jdbc-url}
    catengine-datasource:
        username: root
        password: helloworld
        jdbc-url: jdbc:mysql://kubernetes.docker.internal:3305/coreapi
        url: ${spring.catengine-datasource.jdbc-url}
    flyway:
        enabled: false
    jpa:
        generate-ddl: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
    thymeleaf:
        cache: false
