aws:
    credentials:
        access-key: 'bart'
        secret-key: 'simpson'

spring:
    flyway:
        enabled: false
    jpa:
        generate-ddl: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none

openbanking:
    batch-transactions-refresh-queue: some-queue
