management:
    endpoints:
        web:
            exposure:
                include: info,health
spring:
    datasource:
        password: pwd
        url: jdbc:mysql://localhost:3306/test
        username: user
    jpa:
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
    thymeleaf:
        cache: false
