name: Feature Branch Analysis - Build, UT, IT

on:
  push:
    branches:
      - *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Vars
        id: vars
        run: |
          echo ::set-output name=MVN_PROFILE::test
          echo ::set-output name=JDK_VERSION::11.0.8

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ steps.vars.outputs.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.vars.outputs.JDK_VERSION }}

      - name: Maven Build, Unit Test, Integration Test
        run: mvn -B clean verify --file pom.xml

      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
